const images = import.meta.glob<string>('../assets/drinks/*.png', { eager: true, query: '?url', import: 'default' });
export type Category = 'Beer' | 'Soft drinks' | 'Water' | 'Juice' | 'Energy & sports' | 'Cultured';
export type Drink = { id: string; name: string; year: number; country: string; flag: string; category: Category; type: string; taste: string; story: string; fact: string; image: string; number: number };
const rows: [string,string,number,string,string,Category,string,string,string,string][] = [
['guinness','Guinness',1759,'Ireland','🇮🇪','Beer','Irish dry stout','Roasted · Smooth · Creamy','Arthur Guinness signed a 9,000-year lease on St. James’s Gate in Dublin. His brewery would become one of the world’s most recognizable names.','The signature creamy head comes from a blend of nitrogen and carbon dioxide.'],
['schweppes','Schweppes',1783,'Switzerland','🇨🇭','Soft drinks','Tonic water','Crisp · Bitter · Bubbly','Jacob Schweppe developed a practical way to bottle carbonated water in Geneva, bringing the sparkle of mineral springs to everyday life.','Schweppe moved his business to London in 1792.'],
['evian','Evian',1826,'France','🇫🇷','Water','Natural mineral water','Soft · Clean · Mineral','Bottling began at the Cachat spring near Lake Geneva. This still mineral water originates in the French Alps.','Its water naturally filters through glacial rocks before reaching the spring.'],
['carlsberg','Carlsberg',1847,'Denmark','🇩🇰','Beer','Danish pilsner','Malty · Balanced · Crisp','J.C. Jacobsen established the Copenhagen brewery and named it after his son Carl and the hill on which it stood.','The Carlsberg Laboratory pioneered pure yeast cultivation in brewing.'],
['perrier','Perrier',1863,'France','🇫🇷','Water','Sparkling mineral water','Bold bubbles · Crisp · Mineral','The spring at Vergèze was granted official recognition in 1863. Its distinctive green bottle became a symbol of sparkling refreshment.','The brand’s later name honors physician Louis Perrier.'],
['heineken','Heineken',1873,'Netherlands','🇳🇱','Beer','Dutch pale lager','Malty · Subtle fruit · Bitter','Gerard Adriaan Heineken built a brewing business in Amsterdam with a focus on consistent quality.','Its signature A-Yeast contributes to the beer’s flavor.'],
['budweiser','Budweiser',1876,'United States','🇺🇸','Beer','American pale lager','Light · Clean · Crisp','Introduced by Adolphus Busch and Carl Conrad in St. Louis, Budweiser helped define the American lager style.','Rice is used alongside barley malt for a lighter profile.'],
['dr-pepper','Dr Pepper',1885,'United States','🇺🇸','Soft drinks','23-flavor soda','Spiced · Fruity · Sweet','Pharmacist Charles Alderton created the distinctive soda at Morrison’s Old Corner Drug Store in Waco, Texas.','The famous blend combines 23 flavors; the exact recipe remains a secret.'],
['coca-cola','Coca-Cola',1886,'United States','🇺🇸','Soft drinks','Classic cola','Caramel · Vanilla · Sparkling','John Pemberton served the first Coca-Cola at Jacobs’ Pharmacy in Atlanta. A soda-fountain creation became a global cultural icon.','The instantly recognizable contour bottle was designed in 1915.'],
['pepsi','Pepsi',1893,'United States','🇺🇸','Soft drinks','Classic cola','Citrus · Sweet · Refreshing','Caleb Bradham created “Brad’s Drink” at his pharmacy in New Bern, North Carolina. It was renamed Pepsi-Cola in 1898.','The reference date marks Brad’s Drink, before the Pepsi name arrived.'],
['san-pellegrino','S.Pellegrino',1899,'Italy','🇮🇹','Water','Sparkling mineral water','Fine bubbles · Mineral · Balanced','Commercial bottling began in San Pellegrino Terme, nestled in the Italian Alps.','Its green glass bottle and red star have become dining-table signatures.'],
['canada-dry','Canada Dry',1904,'Canada','🇨🇦','Soft drinks','Ginger ale','Ginger · Crisp · Mellow','John J. McLaughlin introduced a pale, refined ginger ale in Toronto. Its dry character set it apart from heavier ginger drinks.','“Dry” describes its less-sweet style, not an absence of sugar.'],
['corona','Corona',1925,'Mexico','🇲🇽','Beer','Mexican pale lager','Light · Malt · Refreshing','Corona originated at the Cervecería Modelo brewery in Mexico City. Its clear bottle became synonymous with relaxed occasions.','A lime wedge is a popular serving tradition, not an ingredient in the beer.'],
['stella-artois','Stella Artois',1926,'Belgium','🇧🇪','Beer','Belgian pilsner','Floral · Malt · Hoppy','First brewed as a Christmas beer in Leuven, Stella takes its name from the Latin word for star.','The Artois brewery’s roots predate the Stella beer by centuries.'],
['7up','7UP',1929,'United States','🇺🇸','Soft drinks','Lemon-lime soda','Lemon · Lime · Crisp','Charles Leiper Grigg introduced a citrus soda that became one of the enduring names in lemon-lime refreshment.','The original drink had a much longer name: Bib-Label Lithiated Lemon-Lime Soda.'],
['yakult','Yakult',1935,'Japan','🇯🇵','Cultured','Cultured milk drink','Sweet · Tangy · Milky','Microbiologist Minoru Shirota developed a fermented milk drink containing his selected bacterial strain.','Its compact bottle is one of the world’s most recognizable probiotic drink formats.'],
['fanta','Fanta',1940,'Germany','🇩🇪','Soft drinks','Orange soda','Orange · Zesty · Sweet','Fanta began in Germany during wartime ingredient shortages. The orange version familiar today was developed later in Italy.','The name came from the German word Fantasie: imagination.'],
['mountain-dew','Mountain Dew',1942,'United States','🇺🇸','Soft drinks','Citrus soda','Citrus · Bright · Bold','Barney and Ally Hartman developed a citrus soft drink originally intended as a mixer.','The original recipe and branding were very different from the modern drink.'],
['minute-maid','Minute Maid',1946,'United States','🇺🇸','Juice','Orange juice','Orange · Tangy · Smooth','Minute Maid built its early reputation on frozen concentrated orange juice, making juice easier to transport and store.','The name evokes the convenience of preparing juice in a minute.'],
['tropicana','Tropicana',1947,'United States','🇺🇸','Juice','Orange juice','Orange · Sweet · Fresh','Anthony T. Rossi founded Tropicana in Florida, with a focus on bringing orange juice to more households.','Flash pasteurization helped preserve juice while retaining its fresh flavor.'],
['sprite','Sprite',1959,'Germany','🇩🇪','Soft drinks','Lemon-lime soda','Clean · Citrus · Sparkling','Its German predecessor, Fanta Klare Zitrone, arrived in 1959. The Sprite brand launched in the United States in 1961.','The reference date follows the German predecessor rather than the US launch.'],
['gatorade','Gatorade',1965,'United States','🇺🇸','Energy & sports','Sports drink','Fruity · Salty-sweet · Light','A University of Florida research team led by Robert Cade developed a drink for the Florida Gators football team.','The name is a nod to the university’s Gators mascot.'],
['red-bull','Red Bull',1987,'Austria','🇦🇹','Energy & sports','Energy drink','Sweet · Tart · Distinctive','Dietrich Mateschitz and Chaleo Yoovidhya adapted Thailand’s Krating Daeng for an international launch in Austria.','The Austrian launch helped popularize the modern energy-drink category.'],
['powerade','Powerade',1988,'United States','🇺🇸','Energy & sports','Sports drink','Fruit · Sweet · Refreshing','The Coca-Cola Company launched Powerade as a sports beverage with carbohydrates and electrolytes.','Its colorful range became closely associated with major sporting events.'],
['monster-energy','Monster Energy',2002,'United States','🇺🇸','Energy & sports','Energy drink','Bold · Sweet · Citrus','Hansen Natural launched Monster Energy, pairing a distinctive claw-mark identity with music and action-sports culture.','Its black can and vivid green claw logo became its visual signature.'],
];
export const drinks: Drink[] = rows.map(([id,name,year,country,flag,category,type,taste,story,fact],i)=>({id,name,year,country,flag,category,type,taste,story,fact,number:i+1,image:images[`../assets/drinks/${id}.png`] ?? ''}));
export const categories = ['All drinks','Soft drinks','Beer','Water','Juice','Energy & sports','Cultured'] as const;
